const cars = [
  {
    id: 4,
    name: 'Compact Crossover',
    title: 'compact-crossover',
    year: 2021,
    origin: 'South Korea',
    weight: 1400,
    mileage: 8000,
    gearbox: 'Automatic',
    fuel_type: 'Petrol',
    colour: 'Red',
    body_type: 'Crossover',
    engine_size: '1.6L',
    doors: 5,
    seats: 5,
    acceleration: '9.5s',
    fuel_consumption: '6L/100km',
    price: 20000,
    description:
      'This compact crossover is a 2021 model and has 8000 miles on the clock. With an automatic gearbox, it offers a smooth and comfortable driving experience, perfect for city driving. The 1.6L petrol engine is efficient, with a fuel consumption of only 6L/100km. The car is finished in a vibrant red colour and has a practical crossover body type. \n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including a rearview camera, automatic climate control, and a touchscreen infotainment system. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner.',
  },
  {
    id: 5,
    name: 'Electric Hatchback',
    title: 'electric-hatchback',
    year: 2022,
    origin: 'Germany',
    weight: 1300,
    mileage: 5000,
    gearbox: 'Automatic',
    fuel_type: 'Electric',
    colour: 'Silver',
    body_type: 'Hatchback',
    engine_size: 'N/A',
    doors: 5,
    seats: 5,
    acceleration: '8.0s',
    fuel_consumption: '0L/100km',
    price: 35000,
    description:
      'This electric hatchback is a 2022 model and has only 5000 miles on the clock. With an automatic gearbox, it offers a smooth and quiet driving experience, perfect for environmentally conscious drivers. The car is finished in a sleek silver colour and has a practical hatchback body type. \n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including a panoramic sunroof, adaptive cruise control, and a premium sound system. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner.',
  },
  {
    id: 6,
    name: 'Executive Saloon',
    title: 'executive-saloon',
    year: 2022,
    origin: 'United Kingdom',
    weight: 1800,
    mileage: 6000,
    gearbox: 'Automatic',
    fuel_type: 'Petrol',
    colour: 'Grey',
    body_type: 'Saloon',
    engine_size: '2.5L',
    doors: 4,
    seats: 5,
    acceleration: '7.0s',
    fuel_consumption: '8L/100km',
    price: 50000,
    description:
      'This executive saloon is a 2022 model and has only 6000 miles on the clock. With an automatic gearbox, it provides a comfortable and refined driving experience, perfect for business professionals. The 2.5L petrol engine is powerful and efficient, with a fuel consumption of 8L/100km. The car is finished in a classic grey colour and has a stylish saloon body type. \n\nDelivery of this car is available for an additional fee.',
  },
  {
    id: 7,
    name: 'City Car',
    title: 'city-car',
    year: 2021,
    origin: 'Italy',
    weight: 900,
    mileage: 2000,
    gearbox: 'Automatic',
    fuel_type: 'Petrol',
    colour: 'Red',
    body_type: 'Hatchback',
    engine_size: '0.9L',
    doors: 3,
    seats: 4,
    acceleration: '12.0s',
    fuel_consumption: '6L/100km',
    price: 8000,
    description:
      'This city car is a 2022 model and has only 5000 miles on the clock. With an automatic gearbox, it provides a comfortable and efficient driving experience, perfect for city commuters. The 1.0L petrol engine is peppy and efficient, with a fuel consumption of only 6L/100km. The car is finished in a bold red colour and has a practical city car body type.\n\nDelivery of this car is available for an additional fee.',
  },
  {
    id: 9,
    name: 'Compact Sedan',
    title: 'compact-sedan',
    year: 2021,
    origin: 'Japan',
    weight: 1200,
    mileage: 10000,
    gearbox: 'Manual',
    fuel_type: 'Petrol',
    colour: 'Grey',
    body_type: 'Sedan',
    engine_size: '1.8L',
    doors: 4,
    seats: 5,
    acceleration: '10.0s',
    fuel_consumption: '6L/100km',
    price: 15000,
    description:
      'This compact sedan is a 2022 model and has only 8000 miles on the clock. With an automatic gearbox, it provides a comfortable and refined driving experience, perfect for those who value a balance between comfort and practicality. The 1.6L petrol engine is powerful and efficient, with a fuel consumption of 6.5L/100km. The car is finished in a classic silver colour and has a stylish sedan body type.\n\nDelivery of this car is available for an additional fee.',
  },
  {
    id: 10,
    name: 'Muscle Car',
    title: 'muscle-car',
    year: 1970,
    origin: 'USA',
    weight: 1700,
    mileage: 8000,
    gearbox: 'Manual',
    fuel_type: 'Petrol',
    colour: 'Orange',
    body_type: 'Coupe',
    engine_size: '7.0L',
    doors: 2,
    seats: 4,
    acceleration: '6.0s',
    fuel_consumption: '20L/100km',
    price: 250000,
    description:
      'This muscle car is a 2021 model and has only 8000 miles on the clock. With an automatic gearbox, it provides a thrilling and exciting driving experience, perfect for those who love power and speed. The 5.0L petrol engine is incredibly powerful, with a fuel consumption of 10L/100km. The car is finished in a stunning red colour and has a sleek coupe body type.\n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including a premium sound system, sport-tuned suspension, and high-performance brakes. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner.',
  },
  {
    id: 11,
    name: 'Velocity GT',
    title: 'velocity-gt',
    year: 2022,
    origin: 'USA',
    weight: 1800,
    mileage: 3000,
    gearbox: 'Automatic',
    fuel_type: 'Petrol',
    colour: 'Red',
    body_type: 'Coupe',
    engine_size: '3.5L',
    doors: 2,
    seats: 2,
    acceleration: '6.0s',
    fuel_consumption: '9L/100km',
    description:
      'This Velocity GT is a 2022 model and has only 3000 miles on the clock. With an automatic gearbox, it provides a comfortable and refined driving experience, perfect for those who enjoy high speed driving. The 3.5L petrol engine is powerful and efficient, with a fuel consumption of 9L/100km. The car is finished in a vibrant red colour and has a stylish coupe body type. \n\nDelivery of this car is available for an additional fee.',
    price: 45000,
  },
  {
    id: 12,
    name: 'Thunderbolt V8',
    title: 'thunderbolt-v8',
    year: 2022,
    origin: 'USA',
    weight: 2000,
    mileage: 4000,
    gearbox: 'Manual',
    fuel_type: 'Petrol',
    colour: 'Black',
    body_type: 'Coupe',
    engine_size: '4.0L',
    doors: 2,
    seats: 2,
    acceleration: '5.0s',
    fuel_consumption: '10L/100km',
    description:
      'This Thunderbolt V8 is a 2022 model and has only 4000 miles on the clock. With a manual gearbox, it provides a more hands-on driving experience, perfect for those who enjoy high speed driving. The 4.0L petrol engine is powerful and efficient, with a fuel consumption of 10L/100km. The car is finished in a sleek black colour and has a stylish coupe body type. \n\nDelivery of this car is available for an additional fee.',
    price: 48000,
  },
  {
    id: 13,
    name: 'Stealth Mustang',
    title: 'stealth-mustang',
    year: 2021,
    origin: 'USA',
    weight: 1800,
    mileage: 5000,
    gearbox: 'Automatic',
    fuel_type: 'Petrol',
    colour: 'Grey',
    body_type: 'Coupe',
    engine_size: '5.0L',
    doors: 2,
    seats: 4,
    acceleration: '4.0s',
    fuel_consumption: '11L/100km',
    description:
      'This Stealth Mustang is a 2021 model and has only 5000 miles on the clock. With an automatic gearbox, it provides a comfortable and refined driving experience, perfect for those who enjoy high speed driving. The 5.0L petrol engine is powerful and efficient, with a fuel consumption of 11L/100km. The car is finished in a sleek grey colour and has a stylish coupe body type. \n\nDelivery of this car is available for an additional fee.',
    price: 49000,
  },
  {
    id: 14,
    name: 'Jaguar Sprint',
    title: 'jaguar-sprint',
    year: 2021,
    origin: 'UK',
    weight: 1600,
    mileage: 3000,
    gearbox: 'Automatic',
    fuel_type: 'Petrol',
    colour: 'Green',
    body_type: 'Coupe',
    engine_size: '3.0L',
    doors: 2,
    seats: 2,
    acceleration: '5.5s',
    fuel_consumption: '10L/100km',
    description:
      'This sleek coupe is a 2021 model and has only 3000 miles on the clock. With an automatic gearbox, it provides a thrilling driving experience, perfect for those who crave excitement. The 3.0L petrol engine is powerful and efficient, with a fuel consumption of 10L/100km. The car is finished in a stunning green colour and has a classic coupe body type.\n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including a premium sound system, heated front seats, and a sunroof. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner.',
    price: 51000,
  },
  {
    id: 15,
    name: 'Turbocharged Typhoon',
    title: 'turbocharged-typhoon',
    year: 2022,
    origin: 'USA',
    weight: 1800,
    mileage: 8000,
    gearbox: 'Automatic',
    fuel_type: 'Petrol',
    colour: 'Red',
    body_type: 'Coupe',
    engine_size: '2.3L',
    doors: 2,
    seats: 4,
    acceleration: '6.5s',
    fuel_consumption: '8L/100km',
    description:
      'This Turbocharged Typhoon is a 2022 model and has only 8000 miles on the clock. With an automatic gearbox, it provides a fast and thrilling driving experience, perfect for those who value speed and power. The 2.3L petrol engine is turbocharged and efficient, with a fuel consumption of only 8L/100km. The car is finished in a bold red colour and has a sleek coupe body type.\n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including a premium sound system, sporty bucket seats, and a performance-tuned suspension system. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner.',
    price: 34000,
  },
  {
    id: 16,
    name: 'Phoenix Rising',
    title: 'phoenix-rising',
    year: 2022,
    origin: 'Italy',
    weight: 1100,
    mileage: 2000,
    gearbox: 'Automatic',
    fuel_type: 'Petrol',
    colour: 'Red',
    body_type: 'Coupe',
    engine_size: '1.6L',
    doors: 2,
    seats: 2,
    acceleration: '6.5s',
    fuel_consumption: '6L/100km',
    description:
      'The Phoenix Rising is a 2022 model and has only 2000 miles on the clock. With an automatic gearbox, it provides a smooth and effortless driving experience, perfect for those who value comfort and convenience. The 1.6L petrol engine is powerful and efficient, with a fuel consumption of only 6L/100km. The car is finished in a vibrant red colour and has a sleek coupe body type.\n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including a premium sound system, heated front seats, and a sunroof. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner.',
    price: 25000,
  },
  {
    id: 17,
    name: 'Roadster Racer',
    title: 'roadster-racer',
    year: 2022,
    origin: 'USA',
    weight: 1300,
    mileage: 3000,
    gearbox: 'Manual',
    fuel_type: 'Petrol',
    colour: 'Yellow',
    body_type: 'Roadster',
    engine_size: '2.0L',
    doors: 2,
    seats: 2,
    acceleration: '5.5s',
    fuel_consumption: '8L/100km',
    description:
      'The Roadster Racer is a 2022 model and has only 3000 miles on the clock. With a manual gearbox, it offers a more hands-on driving experience, perfect for those who enjoy a bit of driving excitement. The 2.0L petrol engine is powerful and efficient, with a fuel consumption of only 8L/100km. The car is finished in a bold yellow colour and has a classic roadster body type.\n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including a rearview camera, automatic headlamps, and an infotainment system with Apple CarPlay and Android Auto compatibility. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner.',
    price: 39000,
  },
  {
    id: 18,
    name: 'Thunderbird 2.0',
    title: 'thunderbird-2',
    year: 2021,
    origin: 'USA',
    weight: 1800,
    mileage: 3000,
    gearbox: 'Automatic',
    fuel_type: 'Petrol',
    colour: 'Red',
    body_type: 'Convertible',
    engine_size: '2.0L',
    doors: 2,
    seats: 2,
    acceleration: '6.0s',
    fuel_consumption: '9L/100km',
    description:
      'This Thunderbird 2.0 is a 2021 model and has only 3000 miles on the clock. With an automatic gearbox, it provides a smooth and comfortable driving experience, perfect for those who enjoy open-top motoring. The 2.0L petrol engine is powerful and efficient, with a fuel consumption of 9L/100km. The car is finished in a vibrant red colour and has a stylish convertible body type.\n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including a premium sound system, heated seats, and a wind deflector. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner.',
    price: 46000,
  },
  {
    id: 19,
    name: 'Eclipse Turbo',
    title: 'eclipse-turbo',
    year: 2022,
    origin: 'Japan',
    weight: 1500,
    mileage: 8000,
    gearbox: 'Manual',
    fuel_type: 'Petrol',
    colour: 'Red',
    body_type: 'Coupe',
    engine_size: '2.0L',
    doors: 2,
    seats: 4,
    acceleration: '6.5s',
    fuel_consumption: '8L/100km',
    description:
      'This Eclipse Turbo is a 2022 model and has only 8000 miles on the clock. With a manual gearbox, it offers a thrilling driving experience, perfect for those who love speed and performance. The 2.0L turbocharged petrol engine is powerful and efficient, with a fuel consumption of only 8L/100km. The car is finished in a sporty red colour and has a sleek coupe body type.\n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including a premium sound system, sport-tuned suspension, and a sunroof. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner.',
    price: 41000,
  },
  {
    id: 20,
    name: 'Stratosphere Sports',
    title: 'stratosphere-sports',
    year: 2021,
    origin: 'Italy',
    weight: 1200,
    mileage: 6000,
    gearbox: 'Manual',
    fuel_type: 'Petrol',
    colour: 'Yellow',
    body_type: 'Coupe',
    engine_size: '1.8L',
    doors: 2,
    seats: 2,
    acceleration: '5.8s',
    fuel_consumption: '9L/100km',
    description:
      'This Stratosphere Sports is a 2021 model and has only 6000 miles on the clock. With a manual gearbox, it offers a raw and exciting driving experience, perfect for those who enjoy driving for the sake of driving. The 1.8L petrol engine is peppy and efficient, with a fuel consumption of only 9L/100km. The car is finished in a striking yellow colour and has a classic coupe body type.\n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including a sport-tuned exhaust system, Brembo brakes, and a lightweight carbon fiber body. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner.',
    price: 23000,
  },
  {
    id: 21,
    name: 'Viper Venom',
    title: 'viper-venom',
    year: 2021,
    origin: 'USA',
    weight: 1600,
    mileage: 3000,
    gearbox: 'Manual',
    fuel_type: 'Petrol',
    colour: 'Red',
    body_type: 'Sports',
    engine_size: '6.0L',
    doors: 2,
    seats: 2,
    acceleration: '4.0s',
    fuel_consumption: '9L/100km',
    description:
      'The Viper Venom is a 2021 model and has only 3000 miles on the clock. With a manual gearbox, it offers an engaging driving experience, perfect for those who appreciate a bit of driving excitement. The 6.0L petrol engine is powerful and efficient, with a fuel consumption of only 9L/100km. The car is finished in a striking red colour and has a sleek sports body type.\n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including a premium sound system, leather seats, and a backup camera. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner.',
    price: 39000,
  },
  {
    id: 22,
    name: 'Nova Classic',
    title: 'nova-classic',
    year: 1972,
    origin: 'USA',
    weight: 1500,
    mileage: 50000,
    gearbox: 'Automatic',
    fuel_type: 'Petrol',
    colour: 'Yellow',
    body_type: 'Coupe',
    engine_size: '5.7L',
    doors: 2,
    seats: 4,
    acceleration: '9.0s',
    fuel_consumption: '15L/100km',
    description:
      'This classic 1972 Nova is a true American muscle car, with a powerful 5.7L V8 engine under the hood. With an automatic gearbox, it provides a comfortable and effortless driving experience, perfect for cruising on the open road. The car is finished in a bright yellow colour and has a classic coupe body type.\n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including a custom exhaust system, power steering, and air conditioning. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner.',
    price: 24000,
  },
  {
    id: 23,
    name: 'Panthera',
    title: 'panthera',
    year: 2022,
    origin: 'Italy',
    weight: 1500,
    mileage: 1000,
    gearbox: 'Manual',
    fuel_type: 'Petrol',
    colour: 'Red',
    body_type: 'Coupe',
    engine_size: '2.5L',
    doors: 2,
    seats: 2,
    acceleration: '6.0s',
    fuel_consumption: '9L/100km',
    description:
      'This Panthera is a 2022 model and has only 1000 miles on the clock. With a manual gearbox, it offers a more hands-on driving experience, perfect for those who enjoy a bit of driving excitement. The 2.5L petrol engine is powerful and efficient, with a fuel consumption of only 9L/100km. The car is finished in a striking red colour and has a sleek coupe body type.\n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including a rearview camera, automatic climate control, and an infotainment system with Apple CarPlay and Android Auto compatibility. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner.',
    price: 45000,
  },
  {
    id: 24,
    name: 'Redline Raptor',
    title: 'redline-raptor',
    year: 2021,
    origin: 'USA',
    weight: 2500,
    mileage: 15000,
    gearbox: 'Automatic',
    fuel_type: 'Petrol',
    colour: 'Red',
    body_type: 'Pickup',
    engine_size: '5.0L',
    doors: 4,
    seats: 5,
    acceleration: '6.5s',
    fuel_consumption: '12L/100km',
    description:
      'This Redline Raptor is a 2021 model and has 15000 miles on the clock. With an automatic gearbox, it provides a comfortable and smooth driving experience, perfect for those who value convenience and power. The 5.0L petrol engine is incredibly powerful and efficient, with a fuel consumption of only 12L/100km. The car is finished in a vibrant red colour and has a practical pickup body type.\n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including a rearview camera, automatic headlights, and a touchscreen infotainment system. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner.',
    price: 30000,
  },
  {
    id: 25,
    name: 'Mustang Madness',
    title: 'mustang-madness',
    year: 2022,
    origin: 'USA',
    weight: 1800,
    mileage: 5000,
    gearbox: 'Manual',
    fuel_type: 'Petrol',
    colour: 'Red',
    body_type: 'Coupe',
    engine_size: '5.0L',
    doors: 2,
    seats: 4,
    acceleration: '5.0s',
    fuel_consumption: '9L/100km',
    description:
      'This Mustang Madness is a 2022 model and has only 5000 miles on the clock. With a manual gearbox, it offers a more hands-on driving experience, perfect for those who enjoy a bit of driving excitement. The 5.0L petrol engine is powerful and efficient, with a fuel consumption of only 9L/100km. The car is finished in a striking red colour and has a classic coupe body type.\n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including a premium sound system, sport-tuned suspension, and performance brakes. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner.',
    price: 72000,
  },
  {
    id: 26,
    name: 'Genesis GTR',
    title: 'genesis-gtr',
    year: 2021,
    origin: 'South Korea',
    weight: 1650,
    mileage: 3000,
    gearbox: 'Automatic',
    fuel_type: 'Petrol',
    colour: 'Blue',
    body_type: 'Coupe',
    engine_size: '3.8L',
    doors: 2,
    seats: 4,
    acceleration: '4.0s',
    fuel_consumption: '10L/100km',
    description:
      'This Genesis GTR is a 2021 model and has only 3000 miles on the clock. With an automatic gearbox, it provides a smooth and effortless driving experience, perfect for those who value comfort and convenience. The 3.8L petrol engine is powerful and efficient, with a fuel consumption of only 10L/100km. The car is finished in a sleek blue colour and has a sporty coupe body type.\n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including a premium sound system, sport-tuned suspension, and a high-performance braking system. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner.',
    price: 105000,
  },
  {
    id: 27,
    name: 'Torque Titan',
    title: 'torque-titan',
    year: 2022,
    origin: 'USA',
    weight: 2500,
    mileage: 1000,
    gearbox: 'Automatic',
    fuel_type: 'Petrol',
    colour: 'Black',
    body_type: 'Pickup Truck',
    engine_size: '5.7L',
    doors: 4,
    seats: 5,
    acceleration: '7.0s',
    fuel_consumption: '12L/100km',
    description:
      'This Torque Titan is a 2022 model and has only 1000 miles on the clock. With an automatic gearbox, it provides a comfortable and smooth driving experience, perfect for those who love powerful pickup trucks. The 5.7L petrol engine is powerful and efficient, with a fuel consumption of only 12L/100km. The car is finished in a sleek black colour and has a practical pickup truck body type.\n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including a rearview camera, automatic headlamps, and an infotainment system with Apple CarPlay and Android Auto compatibility. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner. The price of this car is 48,000 British pounds.',
  },
  {
    id: 28,
    name: 'Black Knight',
    title: 'black-knight',
    year: 2022,
    origin: 'England',
    weight: 1800,
    mileage: 500,
    gearbox: 'Manual',
    fuel_type: 'Petrol',
    colour: 'Black',
    body_type: 'Coupe',
    engine_size: '3.0L',
    doors: 2,
    seats: 2,
    acceleration: '5.0s',
    fuel_consumption: '10L/100km',
    description:
      'This Black Knight is a 2022 model and has only 500 miles on the clock. With a manual gearbox, it provides a thrilling driving experience, perfect for those who love fast and powerful sports cars. The 3.0L petrol engine is peppy and efficient, with a fuel consumption of only 10L/100km. The car is finished in a sleek black colour and has a classic coupe body type.\n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including a premium sound system, heated front seats, and a sunroof. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner. The price of this car is 52,000 British pounds.',
  },
  {
    id: 29,
    name: 'Apollo Cruiser',
    title: 'apollo-cruiser',
    year: 2022,
    origin: 'Italy',
    weight: 1850,
    mileage: 5000,
    gearbox: 'Automatic',
    fuel_type: 'Petrol',
    colour: 'Red',
    body_type: 'Sedan',
    engine_size: '2.0L',
    doors: 4,
    seats: 5,
    acceleration: '7.5s',
    fuel_consumption: '8L/100km',
    description:
      'This Apollo Cruiser is a 2022 model and has only 5000 miles on the clock. With an automatic gearbox, it offers a smooth and effortless driving experience, perfect for those who value comfort and convenience. The 2.0L petrol engine is peppy and efficient, with a fuel consumption of only 8L/100km. The car is finished in a vibrant red colour and has a classic sedan body type.\n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including a premium sound system, heated front seats, and a sunroof. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner.',
    price: 25000,
  },
  {
    id: 30,
    name: 'Cougar Speedster',
    title: 'cougar-speedster',
    year: 2021,
    origin: 'UK',
    weight: 1200,
    mileage: 6000,
    gearbox: 'Manual',
    fuel_type: 'Petrol',
    colour: 'Green',
    body_type: 'Convertible',
    engine_size: '1.8L',
    doors: 2,
    seats: 2,
    acceleration: '6.0s',
    fuel_consumption: '9L/100km',
    description:
      'This Cougar Speedster is a 2021 model and has only 6000 miles on the clock. With a manual gearbox, it offers a more hands-on driving experience, perfect for those who enjoy a bit of driving excitement. The 1.8L petrol engine is peppy and efficient, with a fuel consumption of only 9L/100km. The car is finished in a striking green colour and has a sporty convertible body type.\n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including a rearview camera, automatic headlamps, and an infotainment system with Apple CarPlay and Android Auto compatibility. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner.',
    price: 30000,
  },
  {
    id: 31,
    name: 'Maverick Mamba',
    title: 'maverick-mamba',
    year: 2021,
    origin: 'USA',
    weight: 1500,
    mileage: 2000,
    gearbox: 'Manual',
    fuel_type: 'Petrol',
    colour: 'Red',
    body_type: 'Coupe',
    engine_size: '5.0L',
    doors: 2,
    seats: 2,
    acceleration: '6.0s',
    fuel_consumption: '10L/100km',
    price: 38000,
    description:
      'This Maverick Mamba is a 2021 model and has only 2000 miles on the clock. With a manual gearbox, it offers a more hands-on driving experience, perfect for those who enjoy a bit of driving excitement. The 5.0L petrol engine is powerful and efficient, with a fuel consumption of only 10L/100km. The car is finished in a striking red colour and has a sporty coupe body type.\n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including a rearview camera, automatic headlamps, and an infotainment system with Apple CarPlay and Android Auto compatibility. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner.',
  },
  {
    id: 32,
    name: 'Cyclone Cruiser',
    title: 'cyclone-cruiser',
    year: 2022,
    origin: 'Japan',
    weight: 1300,
    mileage: 5000,
    gearbox: 'Automatic',
    fuel_type: 'Petrol',
    colour: 'Green',
    body_type: 'Coupe',
    engine_size: '2.0L',
    doors: 2,
    seats: 2,
    acceleration: '7.0s',
    fuel_consumption: '8L/100km',
    price: 25000,
    description:
      'This Cyclone Cruiser is a 2022 model and has 5000 miles on the clock. With an automatic gearbox, it provides a comfortable and smooth driving experience, perfect for those who value ease of use. The 2.0L petrol engine is peppy and efficient, with a fuel consumption of only 8L/100km. The car is finished in a unique green colour and has a sporty coupe body type.\n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including a premium sound system, heated front seats, and a sunroof. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner.',
  },
  {
    id: 33,
    name: 'Velocity Vixen',
    title: 'velocity-vixen',
    year: 2021,
    origin: 'Japan',
    weight: 1300,
    mileage: 5000,
    gearbox: 'Automatic',
    fuel_type: 'Petrol',
    colour: 'Red',
    body_type: 'Coupe',
    engine_size: '2.0L',
    doors: 2,
    seats: 2,
    acceleration: '6.0s',
    fuel_consumption: '8L/100km',
    description:
      'This Velocity Vixen is a 2021 model and has only 5000 miles on the clock. With an automatic gearbox, it offers a smooth and effortless driving experience, perfect for those who value comfort and convenience. The 2.0L petrol engine is powerful and efficient, with a fuel consumption of only 8L/100km. The car is finished in a sleek red colour and has a sporty coupe body type.\n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including a premium sound system, climate control, and a sunroof. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner.',
    price: 40000,
  },
  {
    id: 34,
    name: 'Dragonfire 2.0',
    title: 'dragonfire-2',
    year: 2022,
    origin: 'USA',
    weight: 1700,
    mileage: 10000,
    gearbox: 'Automatic',
    fuel_type: 'Petrol',
    colour: 'Yellow',
    body_type: 'Convertible',
    engine_size: '3.0L',
    doors: 2,
    seats: 2,
    acceleration: '5.0s',
    fuel_consumption: '9L/100km',
    description:
      'This Dragonfire 2.0 is a 2022 model and has 10000 miles on the clock. With an automatic gearbox, it provides a comfortable and smooth driving experience, perfect for those who want a fun and exciting driving experience. The 3.0L petrol engine is powerful and efficient, with a fuel consumption of only 9L/100km. The car is finished in a bright yellow colour and has a stylish convertible body type.\n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including a premium sound system, heated seats, and a navigation system. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner.',
    price: 55000,
  },
  {
    id: 35,
    name: 'Neptune Nemo',
    title: 'neptune-nemo',
    year: 2021,
    origin: 'Italy',
    weight: 1400,
    mileage: 3000,
    gearbox: 'Automatic',
    fuel_type: 'Electric',
    colour: 'Teal',
    body_type: 'Coupe',
    engine_size: 'n/a',
    doors: 2,
    seats: 2,
    acceleration: '4.5s',
    fuel_consumption: '0L/100km',
    description:
      'The Neptune Nemo is a stunning all-electric coupe from Italy. It is a 2021 model and has only 3000 miles on the clock. With an automatic gearbox, it offers a smooth and effortless driving experience. The electric powertrain delivers instant torque and a 0-60 time of just 4.5 seconds. The car is finished in a beautiful teal colour and has a sleek coupe body type.\n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including a premium sound system, heated and ventilated seats, and a panoramic sunroof. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner.',
    price: 75000,
  },
  {
    id: 36,
    name: 'Knight Rider K.I.T.T.',
    title: 'knight-rider-kitt',
    year: 1982,
    origin: 'USA',
    weight: 1700,
    mileage: 12000,
    gearbox: 'Automatic',
    fuel_type: 'Petrol',
    colour: 'Black',
    body_type: 'Coupe',
    engine_size: '5.7L',
    doors: 2,
    seats: 2,
    acceleration: '6.5s',
    fuel_consumption: '15L/100km',
    description:
      'The Knight Rider K.I.T.T. is a classic American coupe from 1982. It has been meticulously maintained and has only 12000 miles on the clock. With an automatic gearbox, it offers a smooth and effortless driving experience. The 5.7L V8 engine is powerful and delivers a satisfying growl. The car is finished in a sleek black colour and has a classic coupe body type.\n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including a high-tech dashboard, voice-activated controls, and a variety of futuristic gadgets. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner.',
    price: 120000,
  },
  {
    id: 37,
    name: 'Bullet Roadster',
    title: 'bullet-roadster',
    year: 2021,
    origin: 'USA',
    weight: 1600,
    mileage: 3000,
    gearbox: 'Automatic',
    fuel_type: 'Petrol',
    colour: 'Red',
    body_type: 'Roadster',
    engine_size: '5.0L',
    doors: 2,
    seats: 2,
    acceleration: '4.0s',
    fuel_consumption: '9L/100km',
    description:
      'This Bullet Roadster is a 2021 model and has only 3000 miles on the clock. With an automatic gearbox, it offers a smooth and effortless driving experience, perfect for those who value comfort and convenience. The 5.0L petrol engine is powerful and efficient, with a fuel consumption of only 9L/100km. The car is finished in a striking red colour and has a classic roadster body type.\n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including a premium sound system, leather seats, and a sport-tuned suspension. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner.',
    price: 58000,
  },
  {
    id: 38,
    name: 'Inferno V8',
    title: 'inferno-v8',
    year: 2022,
    origin: 'Italy',
    weight: 1800,
    mileage: 4000,
    gearbox: 'Automatic',
    fuel_type: 'Petrol',
    colour: 'Orange',
    body_type: 'Coupe',
    engine_size: '6.2L',
    doors: 2,
    seats: 2,
    acceleration: '3.5s',
    fuel_consumption: '12L/100km',
    description:
      'This Inferno V8 is a 2022 model and has only 4000 miles on the clock. With an automatic gearbox, it provides a comfortable and smooth driving experience, perfect for those who enjoy a bit of luxury. The 6.2L petrol engine is incredibly powerful, with a fuel consumption of 12L/100km. The car is finished in a vibrant orange colour and has a sleek coupe body type.\n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including a premium sound system, leather seats, and a performance-tuned exhaust. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner.',
    price: 120000,
  },
  {
    id: 39,
    name: 'Nova Cruiser',
    title: 'nova-cruiser',
    year: 2021,
    origin: 'USA',
    weight: 1400,
    mileage: 5000,
    gearbox: 'Automatic',
    fuel_type: 'Petrol',
    colour: 'Red',
    body_type: 'Coupe',
    engine_size: '2.5L',
    doors: 2,
    seats: 4,
    acceleration: '6.5s',
    fuel_consumption: '8L/100km',
    description:
      'This Nova Cruiser is a 2021 model and has only 5000 miles on the clock. With an automatic gearbox, it offers a smooth and effortless driving experience, perfect for those who value comfort and convenience. The 2.5L petrol engine is powerful and efficient, with a fuel consumption of only 8L/100km. The car is finished in a bold red colour and has a sporty coupe body type.\n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including a premium sound system, leather seats, and a rearview camera. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner.',
    price: 27000,
  },
  {
    id: 40,
    name: 'Firebird Fury',
    title: 'firebird-fury',
    year: 1979,
    origin: 'USA',
    weight: 1600,
    mileage: 80000,
    gearbox: 'Automatic',
    fuel_type: 'Petrol',
    colour: 'Black',
    body_type: 'Coupe',
    engine_size: '6.6L',
    doors: 2,
    seats: 4,
    acceleration: '8.0s',
    fuel_consumption: '15L/100km',
    description:
      'This Firebird Fury is a classic 1979 model and has only 80000 miles on the clock. With an automatic gearbox, it provides a comfortable and smooth driving experience, perfect for those who enjoy a bit of nostalgia. The 6.6L petrol engine is powerful and has a classic V8 rumble, with a fuel consumption of 15L/100km. The car is finished in a sleek black colour and has a sporty coupe body type.\n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including power windows, air conditioning, and a retro-style radio. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner.',
    price: 15000,
  },
];

export default cars;
