const cars = [
  /*  {
    id: 1,
    Name: 'chevrolet-chevelle-malibu',
    title: 'Chevrolet Chevelle Malibu',
    Miles_per_Gallon: 18,
    Cylinders: 8,
    Displacement: 307,
    Horsepower: 130,
    Weight_in_lbs: 3504,
    Acceleration: 12,
    Year: '1970-01-01',
    Origin: 'USA',
    Image: require('../temp-img/luxury-sedan.jpg'),
  },
 */
  {
    id: 1,
    name: 'Luxury Sedan',
    title: 'luxury-sedan',
    year: 2021,
    origin: 'Germany',
    weight: 1700,
    mileage: 5000,
    gearbox: 'Automatic',
    fuel_type: 'Diesel',
    colour: 'Black',
    body_type: 'Sedan',
    engine_size: '2.0L',
    doors: 4,
    seats: 5,
    acceleration: '8.0s',
    fuel_consumption: '5L/100km',
    description:
      'This luxury sedan is a 2021 model and has only 5000 miles on the clock. With an automatic gearbox, it offers a smooth and effortless driving experience, perfect for those who value comfort and convenience. The 2.0L diesel engine is powerful and efficient, with a fuel consumption of only 5L/100km. The car is finished in a sleek black colour and has a classic sedan body type.\n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including a premium sound system, heated front seats, and a sunroof. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner.',
    imageURL: '',
  },
  {
    id: 2,
    name: 'Sporty Hatchback',
    title: 'sporty-hatchback',
    year: 2022,
    origin: 'Japan',
    weight: 1250,
    mileage: 7000,
    gearbox: 'Manual',
    fuel_type: 'Petrol',
    colour: 'Blue',
    body_type: 'Hatchback',
    engine_size: '1.5L',
    doors: 5,
    seats: 5,
    acceleration: '7.5s',
    fuel_consumption: '7L/100km',
    description:
      'This sporty hatchback is a 2022 model and has only 7000 miles on the clock. With a manual gearbox, it offers a more hands-on driving experience, perfect for those who enjoy a bit of driving excitement. The 1.5L petrol engine is peppy and efficient, with a fuel consumption of only 7L/100km. The car is finished in a bright blue colour and has a practical hatchback body type.\n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including a rearview camera, automatic headlamps, and an infotainment system with Apple CarPlay and Android Auto compatibility. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner.',
    imageURL: '',
  },
  {
    id: 3,
    name: 'Family SUV',
    title: 'family-suv',
    year: 2022,
    origin: 'USA',
    weight: 2000,
    mileage: 10000,
    gearbox: 'Automatic',
    fuel_type: 'Petrol',
    colour: 'White',
    body_type: 'SUV',
    engine_size: '3.0L',
    doors: 5,
    seats: 7,
    acceleration: '9.0s',
    fuel_consumption: '7L/100km',
    description:
      'This family SUV is a 2022 model and has 10000 miles on the clock. With an automatic gearbox, it provides a comfortable and smooth driving experience, perfect for families with young children. The 3.0L petrol engine is powerful and efficient, with a fuel consumption of only 7L/100km. The car is finished in a classic white colour and has a spacious SUV body type.\n\nDelivery of this car is available for an additional fee. The car comes with a range of extra features including a premium sound system, heated front seats, and a sunroof. Additionally, the car comes with a comprehensive warranty, providing peace of mind and added security for the new owner.',
    imageURL: '',
  },
];

export default cars;
