const cars = [
  {
    id: 1,
    Name: 'chevrolet-chevelle-malibu',
    title: 'Chevrolet Chevelle Malibu',
    Miles_per_Gallon: 18,
    Cylinders: 8,
    Displacement: 307,
    Horsepower: 130,
    Weight_in_lbs: 3504,
    Acceleration: 12,
    Year: '1970-01-01',
    Origin: 'USA',
    Image: require('../temp-img/chevrolet-chevelle-malibu.jpg'),
  },
  {
    id: 2,
    Name: 'buick-skylark-320',
    title: 'Buick Skylark 320',
    Miles_per_Gallon: 15,
    Cylinders: 8,
    Displacement: 350,
    Horsepower: 165,
    Weight_in_lbs: 3693,
    Acceleration: 11.5,
    Year: '1970-01-01',
    Origin: 'USA',
    Image: require('../temp-img/buick-skylark-320.jpg'),
  },
  {
    id: 3,
    Name: 'plymouth-satellite',
    title: 'Plymouth Satellite',
    Miles_per_Gallon: 18,
    Cylinders: 8,
    Displacement: 318,
    Horsepower: 150,
    Weight_in_lbs: 3436,
    Acceleration: 11,
    Year: '1970-01-01',
    Origin: 'USA',
    Image: require('../temp-img/plymouth-satellite.jpg'),
  },
  {
    id: 4,
    Name: 'amc-rebel-sst',
    title: 'Amc Rebel SST',
    Miles_per_Gallon: 16,
    Cylinders: 8,
    Displacement: 304,
    Horsepower: 150,
    Weight_in_lbs: 3433,
    Acceleration: 12,
    Year: '1970-01-01',
    Origin: 'USA',
    Image: require('../temp-img/amc-rebel-sst.jpg'),
  },
  {
    id: 5,
    Name: 'ford-torino',
    title: 'Ford Torino',
    Miles_per_Gallon: 17,
    Cylinders: 8,
    Displacement: 302,
    Horsepower: 140,
    Weight_in_lbs: 3449,
    Acceleration: 10.5,
    Year: '1970-01-01',
    Origin: 'USA',
    Image: require('../temp-img/ford-torino.jpg'),
  },
  {
    id: 6,
    Name: 'ford-galaxie-500',
    title: 'Ford Galaxie 500',
    Miles_per_Gallon: 15,
    Cylinders: 8,
    Displacement: 429,
    Horsepower: 198,
    Weight_in_lbs: 4341,
    Acceleration: 10,
    Year: '1970-01-01',
    Origin: 'USA',
    Image: require('../temp-img/ford-galaxie-500.jpg'),
  },
  {
    id: 7,
    Name: 'chevrolet-chevelle-malibu',
    title: 'Chevrolet Chevelle Malibu',
    Miles_per_Gallon: 18,
    Cylinders: 8,
    Displacement: 307,
    Horsepower: 130,
    Weight_in_lbs: 3504,
    Acceleration: 12,
    Year: '1970-01-01',
    Origin: 'USA',
    Image: require('../temp-img/chevrolet-chevelle-malibu.jpg'),
  },
  {
    id: 8,
    Name: 'buick-skylark-320',
    title: 'Buick Skylark 320',
    Miles_per_Gallon: 15,
    Cylinders: 8,
    Displacement: 350,
    Horsepower: 165,
    Weight_in_lbs: 3693,
    Acceleration: 11.5,
    Year: '1970-01-01',
    Origin: 'USA',
    Image: require('../temp-img/buick-skylark-320.jpg'),
  },
  {
    id: 9,
    Name: 'plymouth-satellite',
    title: 'Plymouth Satellite',
    Miles_per_Gallon: 18,
    Cylinders: 8,
    Displacement: 318,
    Horsepower: 150,
    Weight_in_lbs: 3436,
    Acceleration: 11,
    Year: '1970-01-01',
    Origin: 'USA',
    Image: require('../temp-img/plymouth-satellite.jpg'),
  },
  {
    id: 10,
    Name: 'amc-rebel-sst',
    title: 'Amc Rebel SST',
    Miles_per_Gallon: 16,
    Cylinders: 8,
    Displacement: 304,
    Horsepower: 150,
    Weight_in_lbs: 3433,
    Acceleration: 12,
    Year: '1970-01-01',
    Origin: 'USA',
    Image: require('../temp-img/amc-rebel-sst.jpg'),
  },
  {
    id: 11,
    Name: 'ford-torino',
    title: 'Ford Torino',
    Miles_per_Gallon: 17,
    Cylinders: 8,
    Displacement: 302,
    Horsepower: 140,
    Weight_in_lbs: 3449,
    Acceleration: 10.5,
    Year: '1970-01-01',
    Origin: 'USA',
    Image: require('../temp-img/ford-torino.jpg'),
  },
  {
    id: 12,
    Name: 'ford-galaxie-500',
    title: 'Ford Galaxie 500',
    Miles_per_Gallon: 15,
    Cylinders: 8,
    Displacement: 429,
    Horsepower: 198,
    Weight_in_lbs: 4341,
    Acceleration: 10,
    Year: '1970-01-01',
    Origin: 'USA',
    Image: require('../temp-img/ford-galaxie-500.jpg'),
  },
  {
    id: 13,
    Name: 'chevrolet-chevelle-malibu',
    title: 'Chevrolet Chevelle Malibu',
    Miles_per_Gallon: 18,
    Cylinders: 8,
    Displacement: 307,
    Horsepower: 130,
    Weight_in_lbs: 3504,
    Acceleration: 12,
    Year: '1970-01-01',
    Origin: 'USA',
    Image: require('../temp-img/chevrolet-chevelle-malibu.jpg'),
  },
  {
    id: 14,
    Name: 'buick-skylark-320',
    title: 'Buick Skylark 320',
    Miles_per_Gallon: 15,
    Cylinders: 8,
    Displacement: 350,
    Horsepower: 165,
    Weight_in_lbs: 3693,
    Acceleration: 11.5,
    Year: '1970-01-01',
    Origin: 'USA',
    Image: require('../temp-img/buick-skylark-320.jpg'),
  },
  {
    id: 15,
    Name: 'plymouth-satellite',
    title: 'Plymouth Satellite',
    Miles_per_Gallon: 18,
    Cylinders: 8,
    Displacement: 318,
    Horsepower: 150,
    Weight_in_lbs: 3436,
    Acceleration: 11,
    Year: '1970-01-01',
    Origin: 'USA',
    Image: require('../temp-img/plymouth-satellite.jpg'),
  },
  {
    id: 16,
    Name: 'amc-rebel-sst',
    title: 'Amc Rebel SST',
    Miles_per_Gallon: 16,
    Cylinders: 8,
    Displacement: 304,
    Horsepower: 150,
    Weight_in_lbs: 3433,
    Acceleration: 12,
    Year: '1970-01-01',
    Origin: 'USA',
    Image: require('../temp-img/amc-rebel-sst.jpg'),
  },
  {
    id: 17,
    Name: 'ford-torino',
    title: 'Ford Torino',
    Miles_per_Gallon: 17,
    Cylinders: 8,
    Displacement: 302,
    Horsepower: 140,
    Weight_in_lbs: 3449,
    Acceleration: 10.5,
    Year: '1970-01-01',
    Origin: 'USA',
    Image: require('../temp-img/ford-torino.jpg'),
  },
  {
    id: 18,
    Name: 'ford-galaxie-500',
    title: 'Ford Galaxie 500',
    Miles_per_Gallon: 15,
    Cylinders: 8,
    Displacement: 429,
    Horsepower: 198,
    Weight_in_lbs: 4341,
    Acceleration: 10,
    Year: '1970-01-01',
    Origin: 'USA',
    Image: require('../temp-img/ford-galaxie-500.jpg'),
  },
  {
    id: 19,
    Name: 'chevrolet-chevelle-malibu',
    title: 'Chevrolet Chevelle Malibu',
    Miles_per_Gallon: 18,
    Cylinders: 8,
    Displacement: 307,
    Horsepower: 130,
    Weight_in_lbs: 3504,
    Acceleration: 12,
    Year: '1970-01-01',
    Origin: 'USA',
    Image: require('../temp-img/chevrolet-chevelle-malibu.jpg'),
  },
  {
    id: 20,
    Name: 'buick-skylark-320',
    title: 'Buick Skylark 320',
    Miles_per_Gallon: 15,
    Cylinders: 8,
    Displacement: 350,
    Horsepower: 165,
    Weight_in_lbs: 3693,
    Acceleration: 11.5,
    Year: '1970-01-01',
    Origin: 'USA',
    Image: require('../temp-img/buick-skylark-320.jpg'),
  },
  {
    id: 21,
    Name: 'plymouth-satellite',
    title: 'Plymouth Satellite',
    Miles_per_Gallon: 18,
    Cylinders: 8,
    Displacement: 318,
    Horsepower: 150,
    Weight_in_lbs: 3436,
    Acceleration: 11,
    Year: '1970-01-01',
    Origin: 'USA',
    Image: require('../temp-img/plymouth-satellite.jpg'),
  },
  {
    id: 22,
    Name: 'amc-rebel-sst',
    title: 'Amc Rebel SST',
    Miles_per_Gallon: 16,
    Cylinders: 8,
    Displacement: 304,
    Horsepower: 150,
    Weight_in_lbs: 3433,
    Acceleration: 12,
    Year: '1970-01-01',
    Origin: 'USA',
    Image: require('../temp-img/amc-rebel-sst.jpg'),
  },
  {
    id: 23,
    Name: 'ford-torino',
    title: 'Ford Torino',
    Miles_per_Gallon: 17,
    Cylinders: 8,
    Displacement: 302,
    Horsepower: 140,
    Weight_in_lbs: 3449,
    Acceleration: 10.5,
    Year: '1970-01-01',
    Origin: 'USA',
    Image: require('../temp-img/ford-torino.jpg'),
  },
  {
    id: 24,
    Name: 'ford-galaxie-500',
    title: 'Ford Galaxie 500',
    Miles_per_Gallon: 15,
    Cylinders: 8,
    Displacement: 429,
    Horsepower: 198,
    Weight_in_lbs: 4341,
    Acceleration: 10,
    Year: '1970-01-01',
    Origin: 'USA',
    Image: require('../temp-img/ford-galaxie-500.jpg'),
  },
];

export default cars;
